import { NextRequest, NextResponse } from 'next/server';
import { supabaseServer } from '@/lib/supabase/server';
import { getAuthenticatedUser } from '@/lib/supabase/auth';

/**
 * GET /api/director-node/assets?graph_id=<uuid>
 * List all assets generated by nodes for a specific graph
 * 
 * NOTE: Temporarily returns empty array until assets.metadata column is added to database
 */
export async function GET(req: NextRequest) {
    try {
        const supabase = await supabaseServer();

        // Get current user FIRST (cached)
        const user = await getAuthenticatedUser(supabase);
        if (!user) {
            console.error('[Director Node Assets] Auth error: No user');
            return NextResponse.json(
                { error: 'Unauthorized - Please log in' },
                { status: 401 }
            );
        }

        // TODO: Add metadata column to assets table first
        // For now, return empty array to avoid 400 error
        console.log('[Director Node Assets] Returning empty array - assets.metadata column not yet added to database');
        return NextResponse.json({ assets: [] });
    } catch (error: any) {
        console.error('[Director Node Assets] GET /assets error:', error);
        return NextResponse.json(
            { error: 'Internal server error' },
            { status: 500 }
        );
    }
}
