import { GoogleGenerativeAI } from "@google/generative-ai";

/**
 * Gemini Client for AAA Image Generation
 * Used for generating professional ad shots
 */

export function createGeminiClient() {
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
        throw new Error('GEMINI_API_KEY not configured in environment variables');
    }

    return new GoogleGenerativeAI(apiKey);
}

/**
 * Generate a single AAA image using Gemini
 * Supports up to 14 reference images (Gemini 3 Pro limit)
 */
export async function generateImage(params: {
    prompt: string;
    referenceImageUrl?: string; // Legacy: single image (backward compatible)
    referenceImageUrls?: string[]; // New: multiple images (up to 14)
    quality?: 'standard' | 'ultra';
}): Promise<{ imageUrl: string; metadata: any }> {
    const genAI = createGeminiClient();
    const model = genAI.getGenerativeModel({
        model: "gemini-2.5-flash-image" // Nano Banana Pro for image generation
    });

    const parts: any[] = [{ text: params.prompt }];

    // Add reference images (support both single and multiple)
    const imageUrls = params.referenceImageUrls ||
        (params.referenceImageUrl ? [params.referenceImageUrl] : []);

    if (imageUrls.length > 0) {
        console.log(`[Gemini] Adding ${imageUrls.length} reference image(s)`);

        // Limit to 14 images (Gemini API limit)
        const limitedUrls = imageUrls.slice(0, 14);

        for (const url of limitedUrls) {
            const imageData = await fetchImageAsBase64(url);
            parts.push({
                inlineData: {
                    mimeType: "image/jpeg",
                    data: imageData
                }
            });
        }
    }

    console.log('[Gemini] Generating image...');

    let result = await model.generateContent({
        contents: [{ role: "user", parts }]
    });

    // Extract image from response
    let candidate = result.response.candidates?.[0];
    if (!candidate) {
        console.error('[Gemini] No candidates in response:', JSON.stringify(result.response, null, 2));
        throw new Error('No image generated by Gemini');
    }

    // FAILSAFE: If IMAGE_OTHER, retry with safer fallback prompt
    if (!candidate.content?.parts && (candidate.finishReason as string) === 'IMAGE_OTHER') {
        console.warn('[Gemini] IMAGE_OTHER detected, retrying with safer fallback prompt...');

        // Safer fallback prompt: remove humans, simpler background
        const fallbackPrompt = `Clean product shot on neutral background.
Product clearly visible.
Professional lighting.
Vertical 9:16.
Product should remain consistent with the uploaded image.`;

        const fallbackParts: any[] = [{ text: fallbackPrompt }];
        if (params.referenceImageUrl) {
            const imageData = await fetchImageAsBase64(params.referenceImageUrl);
            fallbackParts.push({
                inlineData: {
                    mimeType: "image/jpeg",
                    data: imageData
                }
            });
        }

        result = await model.generateContent({
            contents: [{ role: "user", parts: fallbackParts }]
        });

        candidate = result.response.candidates?.[0];
        if (!candidate) {
            throw new Error('No image generated by Gemini (even after fallback retry)');
        }
    }

    // Check if content.parts exists (Gemini may refuse generation)
    if (!candidate.content?.parts) {
        console.error('[Gemini] No content.parts in candidate:', JSON.stringify(candidate, null, 2));

        // Check for safety ratings or other issues
        const finishReason = candidate.finishReason;
        const safetyRatings = candidate.safetyRatings;
        const finishMessage = (candidate as any).finishMessage;

        let errorMsg = 'Gemini did not return image data';
        if (finishReason) errorMsg += ` (finishReason: ${finishReason})`;
        if (finishMessage) errorMsg += ` - ${finishMessage}`;
        if (safetyRatings) errorMsg += ` - Safety ratings: ${JSON.stringify(safetyRatings)}`;

        // Store detailed error for debugging
        const error = new Error(errorMsg) as any;
        error.finishReason = finishReason;
        error.safetyRatings = safetyRatings;
        error.finishMessage = finishMessage;

        throw error;
    }

    const imagePart = candidate.content.parts.find((p: any) => p.inlineData);
    if (!imagePart?.inlineData) {
        console.error('[Gemini] No inlineData in parts:', JSON.stringify(candidate.content.parts, null, 2));
        throw new Error('No image data in Gemini response');
    }

    // Upload using media-store (R2 or Supabase based on config)
    const imageUrl = await uploadGeneratedImage(imagePart.inlineData);

    console.log('[Gemini] Image generated and uploaded successfully');

    return {
        imageUrl,
        metadata: {
            model: "gemini-2.5-flash-image",
            prompt: params.prompt,
            quality: params.quality || 'standard',
            generated_at: new Date().toISOString()
        }
    };
}

/**
 * Fetch image as base64 for Gemini API
 */
async function fetchImageAsBase64(url: string): Promise<string> {
    const response = await fetch(url);
    const buffer = await response.arrayBuffer();
    return Buffer.from(buffer).toString('base64');
}

/**
 * Upload generated image using media-store abstraction
 * This respects the configured storage provider (R2 or Supabase)
 */
async function uploadGeneratedImage(imageData: { mimeType: string; data: string }): Promise<string> {
    const { uploadMedia } = await import('@/lib/storage/media-store');

    // Convert base64 to buffer
    const buffer = Buffer.from(imageData.data, 'base64');

    // Generate unique filename
    const filename = `gemini-shot-${Date.now()}-${Math.random().toString(36).substring(7)}.jpg`;

    console.log('[Gemini] Uploading generated image via media-store...');

    // Upload using media-store (respects R2/Supabase config)
    const result = await uploadMedia({
        buffer,
        filename,
        contentType: imageData.mimeType,
        path: 'ads/shots'
    });

    console.log(`[Gemini] Image uploaded to ${result.provider}: ${result.url}`);

    return result.url;
}
